# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Chat123#
      POSTGRES_USER: chat
      POSTGRES_DB: chatroom

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

  keycloak:
    image: keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 9000:8080
    command: "start-dev"